"""Creazione Tabella user sia per sapienza che per roma3

Revision ID: 6ed9b7f3f49f
Revises: e833fcaf1e10
Create Date: 2025-09-06 13:29:54.021120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed9b7f3f49f'
down_revision = 'e833fcaf1e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roma3_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricola', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('second_name', sa.String(length=30), nullable=True),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roma3_user')),
    sa.UniqueConstraint('email', name=op.f('uq_roma3_user_email')),
    sa.UniqueConstraint('matricola', name=op.f('uq_roma3_user_matricola')),
    sa.UniqueConstraint('username', name=op.f('uq_roma3_user_username'))
    )
    op.create_table('sapienza_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricola', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('second_name', sa.String(length=30), nullable=True),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sapienza_user')),
    sa.UniqueConstraint('email', name=op.f('uq_sapienza_user_email')),
    sa.UniqueConstraint('matricola', name=op.f('uq_sapienza_user_matricola')),
    sa.UniqueConstraint('username', name=op.f('uq_sapienza_user_username'))
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('matricola', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=30), nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('matricola', name=op.f('uq_user_matricola')),
    sa.UniqueConstraint('nickname', name=op.f('uq_user_nickname'))
    )
    op.drop_table('sapienza_user')
    op.drop_table('roma3_user')
    # ### end Alembic commands ###
